### ISSUE TITLE
Separator for ReadableNumber 

### ISSUE THREAD

**Issue by Wulfheart** [RaggiTech/laravel-readable#1]
Not all languages use a ``,`` as a delimiter in numbers. E.g. German uses a ``.`` (``100.000`` instead of ``100,000``, which would mean ``100``).
Here might be an additional parameter helpful.

**Comment by RaggiTech** [comment]
@Wulfheart  **Thank you so much for your enhancement idea.**

I hope this add is useful :
- _$delimiter to Numbers_ 
- _$point, $delimiter to Decimals_

**Comment by Wulfheart** [comment]
I‘m looking forward to it. 

May I ask how you are handling local package development?

**Comment by RaggiTech** [comment]
@Wulfheart Do you mean how i require the package locally ?

**Comment by Wulfheart** [comment]
@RaggiTech General information about local package development.

**Comment by RaggiTech** [comment]
i hope this links are useful for what you want.

https://mauricius.dev/require-a-local-composer-package-for-development
https://wisdmlabs.com/blog/create-package-laravel/
https://laravel.com/docs/7.x/packages
https://medium.com/@andrewhanks2402/step-by-step-guide-to-laravel-package-development-82e2865fb278

**Comment by RaggiTech** [comment]
and i think the best way to understand the package development 
1. clone any repository and study it.
2. create your own and require it locally to test it.
